server:
    servlet:
        context-path: /clintech

## default connection pool
spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: pg_adm123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
            show-sql: true
            database: postgresql
            database-platform: org.hibernate.dialect.PostgreSQLDialect
            open-in-view: false
            generate-ddl: rue